name: Crowdin Upload Source

on:
  push:
    branches:
      - master

jobs:
  upload:
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            crowdin:
              - '**/locales/en/translation.json'

      - name: crowdin action
        if: steps.changes.outputs.crowdin == 'true'
        uses: crowdin/github-action@v1.6.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}